export const RETRIEVE_USER_ASSIGNMENTS = 'RETRIEVE_USER_ASSIGNMENTS';
export const RETRIEVE_ASSIGNMENT_STATS = 'RETRIEVE_ASSIGNMENT_STATS';
export const SELECT_ASSIGNMENT = 'SELECT_ASSIGNMENT';

export const RETRIEVE_USER_MEMBERSHIPS = 'RETRIEVE_USER_MEMBERSHIPS';
export const SET_USER_DATA = 'SET_USER_DATA';

export const SET_LANE_STEP = 'SET_LANE_STEP';
export const SET_LANE_INFO_MODE = 'SET_LANE_INFO_MODE';

export const START_NEW_CALL = 'START_NEW_CALL';
export const SET_CALL_REPORT_FIELD = 'SET_CALL_REPORT_FIELD';
export const SET_CALLER_LOG_MESSAGE = 'SET_CALLER_LOG_MESSAGE';
export const SET_ORGANIZER_LOG_MESSAGE = 'SET_ORGANIZER_LOG_MESSAGE';
