export const RETRIEVE_USER_ASSIGNMENTS = 'RETRIEVE_USER_ASSIGNMENTS';
export const SELECT_ASSIGNMENT = 'SELECT_ASSIGNMENT';

export const SET_USER_DATA = 'SET_USER_DATA';

export const SET_LANE_STEP = 'SET_LANE_STEP';
